### ISSUE TITLE
1.8.8 plugin won't start

### ISSUE THREAD

**Issue by gamerover98** [gamerover98/NoBlackSky#3]
**Spigot version**
CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Console errors**
```
[04:37:29] [Server thread/INFO]: [NoBlackSky] Enabling NoBlackSky v2.1
[04:37:29] [Server thread/ERROR]: Error occurred while enabling NoBlackSky v2.1 (Is it up to date?)
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkNotNull(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
	at it.gamerover.nbs.libs.xyz.tozymc.spigot.api.command.CommandController.registerPluginCommand(CommandController.java:76) ~[?:?]
	at it.gamerover.nbs.libs.xyz.tozymc.spigot.api.command.CommandController.addCommand(CommandController.java:107) ~[?:?]
	at it.gamerover.nbs.command.PluginCommand.<init>(PluginCommand.java:30) ~[?:?]
	at it.gamerover.nbs.NoBlackSky.onEnable(NoBlackSky.java:108) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```

**How to bypass this issue**
Use the 1.1.2 version: https://www.spigotmc.org/resources/no-black-sky-1-7-x-1-16-x-for-void-worlds.25337/history

**Comment by gamerover98** [comment]
### After the updating Commands-API to the 2.0 version, it doesn't work anyway

**Console errors**
```
[04:45:24] [Server thread/INFO]: [NoBlackSky] Enabling NoBlackSky v2.1
[04:45:24] [Server thread/ERROR]: Error occurred while enabling NoBlackSky v2.1 (Is it up to date?)
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V
	at it.gamerover.nbs.libs.xyz.tozymc.spigot.api.command.CommandController.addCommand(CommandController.java:111) ~[?:?]
	at it.gamerover.nbs.command.PluginCommand.<init>(PluginCommand.java:30) ~[?:?]
	at it.gamerover.nbs.NoBlackSky.onEnable(NoBlackSky.java:108) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```
