### ISSUE TITLE
 Unhandled exception occured in onPacketSending(PacketEvent)

### ISSUE THREAD

**Issue by gamerover98** [gamerover98/NoBlackSky#4]
You can find this issue in every version of the server or ProtocolLib plugin.
I don't find a way to fix this.

```
[NoBlackSky] Unhandled exception occured in onPacketSending(PacketEvent) for NoBlackSky
java.lang.UnsupportedOperationException: The method getWorld is not supported for temporary players.
at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.delegate(TemporaryPlayerFactory.java:166) ~[?:?]
at com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler.getWorld(Unknown Source) ~[?:?]
at it.gamerover.nbs.packet.NoBlackSkyAdapter.onPacketSending(NoBlackSkyAdapter.java:75) ~[?:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:434) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:71) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:374) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:344) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:311) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:267) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:243) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1887) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1860) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.PlayerList.a(PlayerList.java:271) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.LoginListener.c(LoginListener.java:189) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.LoginListener.tick(LoginListener.java:87) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:403) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:158) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1501) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1328) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-564]
at java.lang.Thread.run(Thread.java:834) [?:?]
[13:55:03 ERROR]: Parameters:
net.minecraft.server.v1_16_R3.PacketPlayOutLogin@55f82d4c[
a=7971706
b=-1319929221206430238
c=false
d=SURVIVAL
e=NOT_SET
f=[ResourceKey[minecraft:dimension / minecraft:eek:verworld], ResourceKey[minecraft:dimension / minecraft:the_end], ResourceKey[minecraft:dimension / minecraft:galaxyneu], ResourceKey[minecraft:dimension / minecraft:galaxy]]
g=net.minecraft.server.v1_16_R3.IRegistryCustom$Dimension@5e6f6bdf
h=net.minecraft.server.v1_16_R3.DimensionManager@59ea4ca5
i=ResourceKey[minecraft:dimension / minecraft:eek:verworld]
j=64
k=10
l=false
m=true
n=false
o=false
]
```

**Comment by gamerover98** [comment]
I have found a solution from spigot 1.16.
From this version, you will find a new property into "[join game](https://wiki.vg/index.php?title=Protocol&oldid=16681#Join_Game)" and "[Respawn](https://wiki.vg/index.php?title=Protocol&oldid=16681#Respawn)" packets called **Dimension**.

With this property, I've found a different way to get the player's world and its environment.
_And on top of that, ProtocolLib doesn't help me anymore..._

The following piece of code can be found in [FlatNoBlackSkyAdapter class](https://github.com/gamerover98/NoBlackSky/blob/master/support/flat/src/main/java/it/gamerover/nbs/support/flat/packet/FlatNoBlackSkyAdapter.java) and it explains how I have to fix it:

```java
private boolean checkWorldBeforeNetherUpdate(@NotNull PacketContainer packet) {

    int worldDimension = -1;

    /*
     * [Warning]
     *   The following commented piece of code is bugged!
     *
     *   1) The method getDimension() from WrapperPlayServerLogin class is incorrect because
     *      it gets the entity ID instead of the dimension number.
     *      Indicted line (1): worldDimension = wrapperPlayServerLogin.getDimension()
     *
     *      For this reason, according to the protocol 1.15.2 APIs (that you can find
     *      at: https://wiki.vg/index.php?title=Protocol&oldid=16067#Join_Game), the
     *      correct integer field index is 1 and not 0.
     *
     *   2) The method getDimension() from WrapperPlayServerRespawn class throws an error.
     *      Indicted line: worldDimension = wrapperPlayServerRespawn.getDimension()
     *
     * The following solution is for both packets.
     */
    @SuppressWarnings("deprecation") // the getDimensions() method will be removed from ProtocolLib.
    List<Integer> dimensionList = packet.getDimensions().getValues();
    Optional<Integer> optional = dimensionList.stream().findAny();

    if (optional.isPresent()) {
        worldDimension = optional.get();
    }

    return worldDimension == OVERWORLD_DIMENSION;

}
```

**Sadly, there is no way to fix this issue from Spigot before 1.16 due to the packets missing the world name property.**
